/**
 * @author Maria Fernanda Serna
 */

export const MESSAGES_LOAD_REQUEST = 'MESSAGES_LOAD_REQUEST';
export const MESSAGES_LOAD_REQUEST_FAIL = 'MESSAGES_LOAD_REQUEST_FAIL';
export const MESSAGES_LOAD_REQUEST_SUCCESS = 'MESSAGES_LOAD_REQUEST_SUCCESS';

export const MESSAGE_PUT_REQUEST = 'MESSAGE_PUT_REQUEST';
export const MESSAGE_PUT_REQUEST_FAIL = 'MESSAGE_PUT_REQUEST_FAIL';
export const MESSAGE_PUT_REQUEST_SUCCESS = 'MESSAGE_PUT_REQUEST_SUCCESS';