/**
 * @author Maria Fernanda Serna
 */

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_REQUEST_FAIL = 'SIGNIN_REQUEST_FAIL';
export const SIGNIN_REQUEST_SUCCESS = 'SIGNIN_REQUEST_SUCCESS';

export const SESSION_RESTORING = 'SESSION_RESTORING';

export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
export const SIGNOUT_REQUEST_FAIL = 'SIGNOUT_REQUEST_FAIL';
export const SIGNOUT_REQUEST_SUCCESS = 'SIGNOUT_REQUEST_SUCCESS';
